# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_MultiTrack', [dirname(__file__)])
        except ImportError:
            import _MultiTrack
            return _MultiTrack
        if fp is not None:
            try:
                _mod = imp.load_module('_MultiTrack', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _MultiTrack = swig_import_helper()
    del swig_import_helper
else:
    import _MultiTrack
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class MultiTrackStereoManager(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MultiTrackStereoManager, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MultiTrackStereoManager, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _MultiTrack.new_MultiTrackStereoManager(*args)
        try: self.this.append(this)
        except: self.this = this
    def init(self): return _MultiTrack.MultiTrackStereoManager_init(self)
    def updateparam(self, *args): return _MultiTrack.MultiTrackStereoManager_updateparam(self, *args)
    def run(self): return _MultiTrack.MultiTrackStereoManager_run(self)
    def stop_capture(self): return _MultiTrack.MultiTrackStereoManager_stop_capture(self)
    __swig_setmethods__["isRunning"] = _MultiTrack.MultiTrackStereoManager_isRunning_set
    __swig_getmethods__["isRunning"] = _MultiTrack.MultiTrackStereoManager_isRunning_get
    if _newclass:isRunning = _swig_property(_MultiTrack.MultiTrackStereoManager_isRunning_get, _MultiTrack.MultiTrackStereoManager_isRunning_set)
    __swig_destroy__ = _MultiTrack.delete_MultiTrackStereoManager
    __del__ = lambda self : None;
MultiTrackStereoManager_swigregister = _MultiTrack.MultiTrackStereoManager_swigregister
MultiTrackStereoManager_swigregister(MultiTrackStereoManager)

class TrackedObj(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TrackedObj, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TrackedObj, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _MultiTrack.new_TrackedObj(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["loc"] = _MultiTrack.TrackedObj_loc_set
    __swig_getmethods__["loc"] = _MultiTrack.TrackedObj_loc_get
    if _newclass:loc = _swig_property(_MultiTrack.TrackedObj_loc_get, _MultiTrack.TrackedObj_loc_set)
    __swig_setmethods__["spd"] = _MultiTrack.TrackedObj_spd_set
    __swig_getmethods__["spd"] = _MultiTrack.TrackedObj_spd_get
    if _newclass:spd = _swig_property(_MultiTrack.TrackedObj_spd_get, _MultiTrack.TrackedObj_spd_set)
    __swig_destroy__ = _MultiTrack.delete_TrackedObj
    __del__ = lambda self : None;
TrackedObj_swigregister = _MultiTrack.TrackedObj_swigregister
TrackedObj_swigregister(TrackedObj)

# This file is compatible with both classic and new-style classes.


